### ISSUE TITLE
Probably CSS/Bootstrap bug

### ISSUE THREAD

**Issue by vandroids** [knpuniversity/oo#25]
Select dropbox looks like this https://d3.dropfile.to/img/04c03b18612c4920279b9aea053c1fef.png

Windows 7, any browser: latest Chrome, FF & Opera versions.

When I remove "btn-lg" class from select tag it starts to look better.

**Comment by weaverryan** [comment]
Hey @vandroids!

I think you're right! I believe that class is an accident. Fixed at sha: 3f87b58a398079fdadea5675be04832d4502e139

Thanks!
